version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vendas
      POSTGRES_PASSWORD: vendas
      POSTGRES_DB: postgres
    ports:
      - "1333:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data